kind: Pod
apiVersion: v1
metadata:
  name: pod-with-pvc
spec:
  containers:
  - name: pod-with-pvc
    image: gcr.io/google_containers/busybox:1.24
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "touch /mnt/SUCCESS && exit 0 || exit 1"
    # - sleep
    # - "3600"
    volumeMounts:
    - name: pvc
      mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: myclaim