apiVersion: v1
kind: Pod
metadata:
  name: pod-on-low-end-node
  labels:
    role: slow-worker
spec:
  containers:
    - name: website
      image: nginx
      ports:
        - containerPort: 80
  nodeSelector:
    hardware: low