apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-for-service-1
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - redis-for-service-1
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: website
        image: nginx
        ports:
        - name: nginx-port
          containerPort: 80