apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: activemq-access
spec:
  selector:
    matchLabels:
      role: business-service
  env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: activemq-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: activemq-secret
          key: password
